services:
  php:
    build:
      context: .
    ports:
      - '9000:9000'
    volumes:
      - /var/www/app/vendor
      - ./app:/var/www/app

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app/public:/var/www/app/public
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
